// This file is automatically generated from your CSS. Any edits will be overwritten.
export const home: string
export const profileImg: string
export const contentRealm: string
export const postButton: string
export const badgeNew: string
export const postIcon: string