// This file is automatically generated from your CSS. Any edits will be overwritten.
export const container: string;
export const postHeading: string;
export const postContent: string;
export const tagBtn: string;
