stages:
  - quality
  - build
  - release

variables:
  IMAGE_NAME: registry.runway.sh/shamil/personal-website
  IMAGE_TAG: ${CI_COMMIT_SHA}
  KUBERNETES_NAMESPACE: shamil

.cache: &cache
  key: shamilweb_node_modules
  paths:
    - node_modules/

.npm: &npm
  image:
    name: node:10.16.3-alpine
  before_script:
    - apk add --no-cache make git openssh-client
    - mkdir -p ~/.ssh
    - ssh-keyscan -H -t rsa github.com >> ~/.ssh/known_hosts
    - cp ${GITLAB_SHARED_SSH_KEY} ~/.ssh/id_rsa && chmod 400 ~/.ssh/id_rsa
    - npm install

##
## LINT
##

lint:
  <<: *npm
  stage: quality
  cache:
    <<: *cache
  script:
    - npm run lint

##
## TEST
##

test:
  <<: *npm
  stage: quality
  cache:
    <<: *cache
  script:
    - npm run test

##
## BUILD
##

build-app:
  <<: *npm
  stage: build
  artifacts:
    name: ${CI_JOB_STAGE}
    paths:
      - build/
  cache:
    <<: *cache
    policy: pull
  script:
    - npm run build-no-prerender
    - cp -r content build/

##
## RELEASE
##

build-image:
  stage: release
  only: [ master ]
  image:
    name: gcr.io/kaniko-project/executor:debug
  dependencies:
    - build-app
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - cp release/* build/
    - /kaniko/executor
      --cache=true
      --context ${CI_PROJECT_DIR}
      --dockerfile ${CI_PROJECT_DIR}/release/Dockerfile
      --destination ${IMAGE_NAME}:${IMAGE_TAG}
      --destination ${IMAGE_NAME}:latest

deploy_production:
  stage: release
  only: [ master ]
  image: dtzar/helm-kubectl
  environment:
    name: production
    url: https://shamil.co.uk

  script:
    - kubectl config set-cluster k8s --server="${SERVER}"
    - kubectl config set clusters.k8s.certificate-authority-data ${CERTIFICATE_AUTHORITY_DATA}
    - kubectl config set-credentials gitlab-service-account --token="${USER_TOKEN}"
    - kubectl config set-context default --cluster=k8s --user=gitlab-service-account
    - kubectl config use-context default
    - kubectl create secret --namespace=$KUBERNETES_NAMESPACE
                      docker-registry gitlab-registry
                      --docker-server=$CI_REGISTRY
                      --docker-username=${DEPLOY_TOKEN_USERNAME}
                      --docker-password=${DEPLOY_TOKEN_PASSWORD}
                      --docker-email=$GITLAB_USER_EMAIL
                      --output yaml
                      --dry-run | kubectl apply -n $KUBERNETES_NAMESPACE -f -
    - sed -i "s/<VERSION>/${IMAGE_TAG}/g" kubernetes/overlays/production/kustomization.yaml
    - kubectl apply --dry-run -k kubernetes/overlays/production
    - kubectl apply -k kubernetes/overlays/production
